name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting message
        run: echo 'Hello greetings'
      - name: Print second message 
        run: echo'This is the second message, this is the second step of the first job'
